### PR TITLE
Add recoverCatching

### PR DESCRIPTION
**Pull request by berikv**
recoverCatching tries to recover, exceptions in transformation cause an error result.

### CODE REVIEW

**Comment by michaelbull** [comment]
Could you add unit tests too please, ideally alongside the [existing recover-related tests](https://github.com/michaelbull/kotlin-result/blob/3efefdb18b50561aab0e67f30aa56fd09c65b64f/kotlin-result/src/commonTest/kotlin/com/github/michaelbull/result/OrTest.kt#L67)

**Comment by berikv** [comment]
@michaelbull When running allTests locally I get errors on ChromeHeadless. I expect that they are unrelated to my code. Could you verify?

**Comment by michaelbull** [comment]
Approved the run to build on CI, which should help identify anything platform specific

**Comment by berikv** [comment]
The publish ci action is skipped, the others ran successfully

**Comment by michaelbull** [comment]
Merged in a6eb86da71e0db1386f2b013eba31f12c53cc6b5. Should be in the latest snapshot release if you'd like to start playing with it. Cheers.

**Comment by michaelbull** [comment]
Released in v1.1.17.

**Pull request closed without merging**
